[package]
description = "enhanced web framework based on actix-web"
edition = "2021"
name = "gotcha"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-service = "2"
async-trait = "0.1.60"
clap = { version = "4.0.32", features = ["derive"] }
config = {version = "0.13", default-feature = false, features = ["toml"]}
gotcha_lib = {path = "../gotcha_lib"}
gotcha_macro = {path = "../gotcha_macro"}
serde = "1"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
log = "0.4"
