[package]
name = "gotcha"
description = "enhanced web framework based on actix-web"
edition = "2021"
version = "0.1.10"
license = "MIT"
repository = "https://github.com/Kilerd/gotcha/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-service = "2"
async-trait = "0.1.60"
clap = { version = "4.0.32", features = ["derive"] }
config = { version = "0.13", default-feature = false, features = ["toml"] }
gotcha_macro = { version = "0.1", path = "../gotcha_macro" }
gotcha_core = { version = "0.1", path = "../gotcha_core" }
serde = "1"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
log = "0.4"
cron = "0.12.0"
chrono = "0.4.23"
http = "0.2"
oas = "0.1"

[dev-dependencies]
trybuild = "1.0"
serde_json = "1"

