[package]
name = "gotcha"
description = "enhanced web framework based on actix-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
gotcha_macro = { path = "../gotcha_macro" }
gotcha_lib = { path = "../gotcha_lib" }