#:schema node_modules/wrangler/config-schema.json
name = "ghostwriting-ai"
compatibility_date = "2024-12-30"
main = "build/worker/shim.mjs"
compatibility_flags = ["nodejs_compat"]


[build]
command = "cargo install worker-build && worker-build --release"